version: '3.2'

services:

  workers_hierarchy_app: &app
    tty: true
    cap_add:
     - SYS_PTRACE
    build:
      context: .
      args:
        requirements: requirements/development.txt
    container_name: workers_hierarchy
    environment:
      # use in code
      - DEBUG=True
      - SETTINGS_FILE=api.dev.yml
      - PYTHONUNBUFFERED=1
    restart: always
    volumes:
      - .:/app:delegated
    depends_on:
      - postgres
    ports:
      - 8080:8080
      - 8081:8081
    command: make adev

  postgres:
      image: postgres:10
      container_name: workers_hierarchy_postgres
      environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=postgres
      ports:
          - 5432

